use QL_ANHNGU
go

ALTER TABLE LOP_HOC
DROP CONSTRAINT FK_LOPHOC_CTHOC,FK_LOPHOC_GIANGVIEN,FK_LOPHOC_PHONG

ALTER TABLE LOP_HOC
ADD CONSTRAINT FK_LOPHOC_CTHOC foreign key (MaCTHoc) references CHUONG_TRINH_HOC(MaCTHoc) 

ALTER TABLE LOP_HOC
ADD CONSTRAINT FK_LOPHOC_GIANGVIEN foreign key (MaGV) references GIANG_VIEN(MaGiangVien) 

ALTER TABLE LOP_HOC
ADD CONSTRAINT FK_LOPHOC_PHONG foreign key (MaPhong) references PHONG(MaPhong) 



